ExUnit.start()
Application.ensure_all_started(:bypass)
Application.put_env(:keenex, :project_id, "project_id")
Application.put_env(:keenex, :write_key, "write_key")
Application.put_env(:keenex, :read_key, "read_key")
